// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var $$Array            = require("bs-platform/lib/js/array.js");
var Js_null            = require("bs-platform/lib/js/js_null.js");
var Js_boolean         = require("bs-platform/lib/js/js_boolean.js");
var ReasonReact        = require("reason-react/src/ReasonReact.js");
var SpectacleCodeSlide = require("spectacle-code-slide");

function rangeToJs(range) {
  return {
          loc: range[/* loc */0],
          title: Js_null.from_opt(range[/* title */1]),
          note: Js_null.from_opt(range[/* note */2])
        };
}

function make(lang, code, ranges, $staropt$star, children) {
  var showLineNumbers = $staropt$star ? $staropt$star[0] : /* true */1;
  return ReasonReact.wrapJsForReason(SpectacleCodeSlide, {
              lang: lang,
              code: code,
              transition: /* array */[],
              ranges: $$Array.map(rangeToJs, ranges),
              showLineNumbers: Js_boolean.to_js_boolean(showLineNumbers)
            }, children);
}

exports.rangeToJs = rangeToJs;
exports.make      = make;
/* ReasonReact Not a pure module */
