// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Js_null = require("bs-platform/lib/js/js_null.js");
var Js_option = require("bs-platform/lib/js/js_option.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var SpectacleCodeSlide = require("spectacle-code-slide");

function rangeToJs(range) {
  return {
          loc: range[/* loc */0],
          title: Js_null.fromOption(range[/* title */1]),
          note: Js_null.fromOption(range[/* note */2])
        };
}

function mapRangesToJs(rangesOpt) {
  return Js_option.map((function (ranges) {
                return $$Array.map(rangeToJs, ranges);
              }), rangesOpt);
}

function make(lang, code, ranges, showLineNumbers, children) {
  var tmp = {
    lang: lang,
    code: code,
    transition: /* array */[]
  };
  var tmp$1 = mapRangesToJs(ranges);
  if (tmp$1) {
    tmp.ranges = tmp$1[0];
  }
  if (showLineNumbers) {
    tmp.showLineNumbers = showLineNumbers[0];
  }
  return ReasonReact.wrapJsForReason(SpectacleCodeSlide, tmp, children);
}

exports.rangeToJs = rangeToJs;
exports.mapRangesToJs = mapRangesToJs;
exports.make = make;
/* ReasonReact Not a pure module */
